stages:
- name: BuildInitContainer
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile.diesel
      buildContext: .
      tag: bewerkdemarkten-init:${CICD_EXECUTION_SEQUENCE}
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: bewerkdemarkten-api:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 45
branch:
  include:
  - master
notification: {}